##服务配合
server:
  port: 18082
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth_system?&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: testDruidDataSource
      initial-size: 5
      max-active: 20
      min-idle: 5
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 1000
      connection-properties: druid.stat.mergeSql=true
      max-wait: 6000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid123456
        allow: 127.0.0.1
        deny:
      aop-patterns: com.auth.web.service.*
  #redis配置
  redis:
    host: 127.0.0.1
    password: cdn123456
    port: 7001
    database: 0
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: 10000
        min-idle: 0
        max-idle: 8
      #参数意义：
      #JsonInclude.Include.ALWAYS              默认
    #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，SNAKE_CASE-返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式
    property-naming-strategy: SNAKE_CASE
    # 当地时区
    locale: zh
    default-property-inclusion: NON_NULL #不为空的属性才会序列化,具体属性可看JsonInclude.Include
  session:
    store-type: redis
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:com/auth/web/dao/mapper/*.xml
  type-aliases-package: com.auth.web.entity
  global-config:
    #mybatis-plus 3.0+判空
    db-config:
      select-strategy: not_null
      insert-strategy: not_null
      update-strategy: not_null
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2.xml